services:
  # Serviço de Banco de Dados MySQL
  mysql_db: # Nome do serviço alterado para refletir MySQL
    image: mysql:8.0 # Imagem do MySQL, versão 8.0 é uma boa escolha
    container_name: mysql_db_container # Nome do container alterado
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Defina uma senha segura para o root
      MYSQL_DATABASE: serviceDB # Nome da base de dados que a aplicação usará
      MYSQL_USER: admin # Utilizador da aplicação (será criado com esta senha)
      MYSQL_PASSWORD: admin123 # Senha para o utilizador da aplicação
    ports:
      - "3307:3307" # Porta padrão do MySQL
    volumes:
      - mysql_data:/var/lib/mysql # Volume para persistência de dados do MySQL
    networks:
      - app_network

  # Serviço Backend (Spring Boot)
  backend:
    build:
      context: ./customer_service_back
      dockerfile: Dockerfile 
    container_name: customer_service_back
    depends_on:
      - mysql_db # Depende do serviço mysql_db
    environment:
      # URL de conexão JDBC para MySQL, apontando para o nome do serviço do banco de dados
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/serviceDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin # Utilizador definido no serviço mysql_db
      SPRING_DATASOURCE_PASSWORD: admin123 # Senha definida no serviço mysql_db
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update 
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect # Dialeto MySQL
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app_network

  # Serviço Frontend (React/Vite)
  frontend:
    build:
      context: ./customer_service_front
      dockerfile: Dockerfile
    container_name: customer_service_front
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./customer_service_front:/app 
      - /app/node_modules # Adiciona este volume para evitar que node_modules local sobrescreva o do container
    environment:
      # VITE_API_URL aponta para o serviço backend dentro da rede Docker
      # VITE_API_URL: http://backend:8080 
      NODE_ENV: development
    command: sh -c "npm install && npm run dev -- --host"
    networks: 
      - app_network

volumes:
  mysql_data: # Volume nomeado para MySQL

networks:
  app_network:
    driver: bridge