# application.properties

# Configuracoes JWT (mantido como antes)
app.jwt.expiration-ms=86400000
app.jwt.cookie-name=meuapp-jwt

spring.application.name=customer_service

# As configuracoes do banco de dados (URL, username, password) sao fornecidas
# por variaveis de ambiente no docker-compose.yml ou painel do Render.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/customer_service}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=update


# Configuracoes do JPA / Hibernate para MySQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
 # 'update' e geralmente seguro para desenvolvimento. Considere 'validate' ou 'none' para producao.
# A propriedade spring.jpa.database-platform nao e estritamente necessaria se o dialeto estiver correto,
# mas se quiser ser explicito:
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Configuracoes do servidor (mantido como antes)
server.port=8080

management.endpoints.web.exposure.include=*
management.endpoint.mappings.access=UNRESTRICTED
