# application.properties

# Configuracoes JWT (mantido como antes)
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=86400000
app.jwt.cookie-name=meuapp-jwt

spring.application.name=customer_service

# Configuracoes do banco de dados MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracoes do JPA / Hibernate para MySQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
 # 'update' e geralmente seguro para desenvolvimento. Considere 'validate' ou 'none' para producao.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# A propriedade spring.jpa.database-platform nao e estritamente necessaria se o dialeto estiver correto,
# mas se quiser ser explicito:
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Configuracoes do servidor (mantido como antes)
server.port=8080

management.endpoints.web.exposure.include=*
management.endpoint.mappings.access=UNRESTRICTED
