# application.properties

# Configura JWT

app.jwt.secret=WK5lpa4qL0vXn7e87Q6frMwQ6b8g0VVqHCFBZIXyYkEZ+yy5kPFc0ic72yzC/w+zVDiuyhjntSlkb8Vfn2xdBA==
# 24 horas em milissegundos (1 dia * 24 horas * 60 min * 60 seg * 1000 ms)
app.jwt.expiration-ms=86400000
# Nome do cookie se for usar transporte por cookie (opcional)
app.jwt.cookie-name=meuapp-jwt


spring.application.name=customer_service

# Configura do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/serviceDB
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura do JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configura do servidor
server.port=8080

management.endpoints.web.exposure.include=*
management.endpoint.mappings.access=UNRESTRICTED